// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_UTNGolMundial.Data;

#nullable disable

namespace MiApi.UTNGolMundial.Migrations
{
    [DbContext(typeof(MiApiUTNGolMundialContext))]
    [Migration("20260721213827_GolesNullableYEliminada")]
    partial class GolesNullableYEliminada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UTNGolMundial.Modelos.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DatosAnteriores")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatosNuevos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RegistroId")
                        .HasColumnType("integer");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAccionAuditoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Fase", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.ToTable("Fases");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Grupo", b =>
                {
                    b.Property<char>("Codigo")
                        .HasColumnType("character(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaseCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPartido")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<char>("GrupoCodigo")
                        .HasColumnType("character(1)");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPartidoFifa")
                        .HasColumnType("integer");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FaseCodigo");

                    b.HasIndex("GrupoCodigo");

                    b.HasIndex("LocalId");

                    b.HasIndex("SedeId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Rol", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadAproximada")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Seleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoFifa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Confederacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Eliminada")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsAnfitrion")
                        .HasColumnType("boolean");

                    b.Property<char>("GrupoCodigo")
                        .HasColumnType("character(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clasificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCodigo");

                    b.ToTable("Selecciones");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("RolId")
                        .HasColumnType("smallint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Auditoria", b =>
                {
                    b.HasOne("UTNGolMundial.Modelos.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Partido", b =>
                {
                    b.HasOne("UTNGolMundial.Modelos.Fase", "Fase")
                        .WithMany("Partidos")
                        .HasForeignKey("FaseCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Grupo", "Grupo")
                        .WithMany("Partidos")
                        .HasForeignKey("GrupoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Seleccion", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Sede", "Sede")
                        .WithMany("Partidos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Seleccion", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fase");

                    b.Navigation("Grupo");

                    b.Navigation("Local");

                    b.Navigation("Sede");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Seleccion", b =>
                {
                    b.HasOne("UTNGolMundial.Modelos.Grupo", "Grupo")
                        .WithMany("Selecciones")
                        .HasForeignKey("GrupoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Usuario", b =>
                {
                    b.HasOne("UTNGolMundial.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Fase", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Grupo", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("Selecciones");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Sede", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Usuario", b =>
                {
                    b.Navigation("Auditorias");
                });
#pragma warning restore 612, 618
        }
    }
}
