// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_UTNGolMundial.Data;

#nullable disable

namespace MiApi.UTNGolMundial.Migrations
{
    [DbContext(typeof(MiApiUTNGolMundialContext))]
    partial class MiApiUTNGolMundialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UTNGolMundial.Modelos.Fase", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.ToTable("Fases");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Grupo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<char>("Nombre")
                        .HasColumnType("character(1)");

                    b.HasKey("Codigo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("FaseCodigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPartido")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoCodigo")
                        .HasColumnType("integer");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPartidoFifa")
                        .HasColumnType("integer");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FaseCodigo");

                    b.HasIndex("GrupoCodigo");

                    b.HasIndex("LocalId");

                    b.HasIndex("SedeId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadAproximada")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Seleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoFifa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Confederacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsAnfitrion")
                        .HasColumnType("boolean");

                    b.Property<int>("GrupoCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clasificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCodigo");

                    b.ToTable("Selecciones");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Partido", b =>
                {
                    b.HasOne("UTNGolMundial.Modelos.Fase", "Fase")
                        .WithMany("Partidos")
                        .HasForeignKey("FaseCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Grupo", "Grupo")
                        .WithMany("Partidos")
                        .HasForeignKey("GrupoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Seleccion", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Sede", "Sede")
                        .WithMany("Partidos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.Modelos.Seleccion", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fase");

                    b.Navigation("Grupo");

                    b.Navigation("Local");

                    b.Navigation("Sede");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Seleccion", b =>
                {
                    b.HasOne("UTNGolMundial.Modelos.Grupo", "Grupo")
                        .WithMany("Selecciones")
                        .HasForeignKey("GrupoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Fase", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Grupo", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("Selecciones");
                });

            modelBuilder.Entity("UTNGolMundial.Modelos.Sede", b =>
                {
                    b.Navigation("Partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
